QuEST_internal.h File Reference
Internal functions used to implement the public facing API in qubits.h.
#include `QuEST_precision.h`
Functions
void phaseGate (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
REAL findProbabilityOfZero (MultiQubit multiQubit, const int measureQubit)
Measure the probability of a specified qubit being in the zero state.
REAL measureInZero (MultiQubit multiQubit, const int measureQubit)
Update the state vector to be consistent with measuring measureQubit=0.
int validateMatrixIsUnitary (ComplexMatrix2 u)
int validateAlphaBeta (Complex alpha, Complex beta)
int validateUnitVector (REAL ux, REAL uy, REAL uz)
void exitWithError (int errorCode, const char *func)
void QuESTAssert (int isValid, int errorCode, const char *func)
unsigned long int hashString (char *str)
Variables
const char * errorCodes []
Detailed Description
Internal functions used to implement the public facing API in qubits.h.
Do not call these functions directly.
Function Documentation
exitWithError()
void exitWithError (int errorCode, const char * func)
findProbabilityOfZero()
REAL findProbabilityOfZero (MultiQubit multiQubit, const int measureQubit)
Measure the probability of a specified qubit being in the zero state.
Parameters
in multiQubit object representing the set of qubits
in measureQubit qubit to measure
Returns
probability of qubit measureQubit being zero
hashString()
unsigned long int hashString (char * str)
Definition at line 238 of file QuEST.cpp.
Referenced by QuESTSeedRandomDefault().
                                       {
    unsigned long int hash = 5381;
    int c;
    while ((c = *str++))
        hash = ((hash << 5) + hash) + c; /* hash * 33 + c */
    return hash;
}
measureInZero()
REAL measureInZero (MultiQubit multiQubit, const int measureQubit)
Update the state vector to be consistent with measuring measureQubit=0.
Measure in Zero performs an irreversible change to the state vector: it updates the vector according to the event that a zero have been measured on the qubit indicated by measureQubit (where his label starts from 0, of course). It achieves this by setting all inconsistent amplitudes to 0 and then renormalising based on the total probability of measuring measureQubit=0. It then returns the probability of making this measurement.
Parameters
in,out multiQubit object representing the set of qubits
in measureQubit qubit to measure
Returns
probability of qubit measureQubit being zero
phaseGate()
void phaseGate (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Referenced by sGate(), sigmaZ(), and tGate().
QuESTAssert()
void QuESTAssert (int isValid, int errorCode, const char * func)
validateAlphaBeta()
int validateAlphaBeta (Complex alpha, Complex beta)
Definition at line 193 of file QuEST.cpp.
References Complex::imag, Complex::real, and REAL_EPS.
                                                  {
    if (fabs(alpha.real*alpha.real
        + alpha.imag*alpha.imag
        + beta.real*beta.real
        + beta.imag*beta.imag - 1) > REAL_EPS) return 0;
    else return 1;
}
validateMatrixIsUnitary()
int validateMatrixIsUnitary (ComplexMatrix2 u)
Definition at line 168 of file QuEST.cpp.
References Complex::imag, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, Complex::real, and REAL_EPS.
                                             {
    if (fabs(u.r0c0.real*u.r0c0.real
        + u.r0c0.imag*u.r0c0.imag
        + u.r1c0.real*u.r1c0.real
        + u.r1c0.imag*u.r1c0.imag - 1) > REAL_EPS) return 0;
    // check
    if (fabs(u.r0c1.real*u.r0c1.real
        + u.r0c1.imag*u.r0c1.imag
        + u.r1c1.real*u.r1c1.real
        + u.r1c1.imag*u.r1c1.imag - 1) > REAL_EPS) return 0;
    if (fabs(u.r0c0.real*u.r0c1.real
        + u.r0c0.imag*u.r0c1.imag
        + u.r1c0.real*u.r1c1.real
        + u.r1c0.imag*u.r1c1.imag) > REAL_EPS) return 0;
    if (fabs(u.r0c1.real*u.r0c0.imag
        - u.r0c0.real*u.r0c1.imag
        + u.r1c1.real*u.r1c0.imag
        - u.r1c0.real*u.r1c1.imag) > REAL_EPS) return 0;
    return 1;
}
validateUnitVector()
int validateUnitVector (REAL ux, REAL uy, REAL uz)
Definition at line 201 of file QuEST.cpp.
References REAL_EPS.
                                                 {
    if (fabs(sqrt(ux*ux + uy*uy + uz*uz) - 1) > REAL_EPS) return 0;
    else return 1;
}
Variable Documentation
errorCodes
const char* errorCodes[]
Definition at line 24 of file QuEST.cpp.