tutorialExample.cpp File Reference
#include <stdio.h>
#include `QuEST/qubits.h`
Functions
int main (int narg, char *varg[])
Function Documentation
main()
int main (int narg, char * varg[])
Definition at line 4 of file tutorialExample.cpp.
References closeQuESTEnv(), compactUnitary(), controlledNot(), controlledRotateY(), createMultiQubit(), destroyMultiQubit(), findProbabilityOfOutcome(), hadamard(), Complex::imag, initQuESTEnv(), initStateZero(), Complex::real, REAL, reportMultiQubitParams(), reportQuESTEnv(), rotateAroundAxis(), Vector::x, Vector::y, and Vector::z.
                                  {
    /*
     * PREPARE QuEST environment
     * (Required only once per program)
     */
    QuESTEnv env;
    initQuESTEnv(&env);
    printf("-------------------------------------------------------\n");
    printf("Running QuEST tutorial:\n\t Basic circuit involving a system of 3 qubits.\n");
    printf("-------------------------------------------------------\n");
    /*
     * PREPARE QUBIT SYSTEM
     */
    MultiQubit qubits;
    createMultiQubit(&qubits, 3, env);
    initStateZero(&qubits);
    /*
     * REPORT SYSTEM AND ENVIRONMENT
     */
    printf("\nThis is our environment:\n");
    reportMultiQubitParams(qubits);
    reportQuESTEnv(env);
    /*
     * APPLY CIRCUIT
     */
        
        hadamard(qubits, 0);
    controlledNot(qubits, 0, 1);
        
        controlledRotateY(qubits, 0, 2, 0.3);
    Complex a, b;
    a.real = .5; a.imag = .5;
    b.real = .5; b.imag = -.5;
    compactUnitary(qubits, 1, a, b);
    Vector v;
    v.x = 1; v.y = 0; v.z = 0;
    rotateAroundAxis(qubits, 2, 3.14/2, v);
    printf("\nCircuit output:\n");
    REAL prob = findProbabilityOfOutcome(qubits, 2, 1);
    printf("Probability of qubit 2 being in state 1: %f\n", prob);
    /*
     * FREE MEMORY
     */
    destroyMultiQubit(qubits, env);
    /*
     * CLOSE QUEST ENVIRONMET
     * (Required once at end of program)
     */
    closeQuESTEnv(env);
    return 0;
}